/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FoodRouteImport } from './routes/food'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as ActivitiesIndexRouteImport } from './routes/activities.index'
import { Route as ActivitiesActivityIdRouteImport } from './routes/activities.$activityId'
import { Route as TimelineMomentIdRouteImport } from './routes/timeline.$momentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActivitiesRoute,
} as any)
const ActivitiesActivityIdRoute = ActivitiesActivityIdRouteImport.update({
  id: '/$activityId',
  path: '/$activityId',
  getParentRoute: () => ActivitiesRoute,
} as any)
const TimelineMomentIdRoute = TimelineMomentIdRouteImport.update({
  id: '/timeline/$momentId',
  path: '/timeline/$momentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/builder': typeof BuilderRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/food': typeof FoodRoute
  '/preview': typeof PreviewRoute
  '/shopping-list': typeof ShoppingListRoute
  '/todo': typeof TodoRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/timeline/$momentId': typeof TimelineMomentIdRoute
  '/activities/': typeof ActivitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/food': typeof FoodRoute
  '/preview': typeof PreviewRoute
  '/shopping-list': typeof ShoppingListRoute
  '/todo': typeof TodoRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/timeline/$momentId': typeof TimelineMomentIdRoute
  '/activities': typeof ActivitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/builder': typeof BuilderRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/food': typeof FoodRoute
  '/preview': typeof PreviewRoute
  '/shopping-list': typeof ShoppingListRoute
  '/todo': typeof TodoRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/timeline/$momentId': typeof TimelineMomentIdRoute
  '/activities/': typeof ActivitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/builder'
    | '/checkout'
    | '/dashboard'
    | '/food'
    | '/preview'
    | '/shopping-list'
    | '/todo'
    | '/activities/$activityId'
    | '/timeline/$momentId'
    | '/activities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/checkout'
    | '/dashboard'
    | '/food'
    | '/preview'
    | '/shopping-list'
    | '/todo'
    | '/activities/$activityId'
    | '/timeline/$momentId'
    | '/activities'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/builder'
    | '/checkout'
    | '/dashboard'
    | '/food'
    | '/preview'
    | '/shopping-list'
    | '/todo'
    | '/activities/$activityId'
    | '/timeline/$momentId'
    | '/activities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRouteWithChildren
  BuilderRoute: typeof BuilderRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  FoodRoute: typeof FoodRoute
  PreviewRoute: typeof PreviewRoute
  ShoppingListRoute: typeof ShoppingListRoute
  TodoRoute: typeof TodoRoute
  TimelineMomentIdRoute: typeof TimelineMomentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/activities/$activityId': {
      id: '/activities/$activityId'
      path: '/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof ActivitiesActivityIdRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/timeline/$momentId': {
      id: '/timeline/$momentId'
      path: '/timeline/$momentId'
      fullPath: '/timeline/$momentId'
      preLoaderRoute: typeof TimelineMomentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ActivitiesRouteChildren {
  ActivitiesActivityIdRoute: typeof ActivitiesActivityIdRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
}

const ActivitiesRouteChildren: ActivitiesRouteChildren = {
  ActivitiesActivityIdRoute: ActivitiesActivityIdRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
}

const ActivitiesRouteWithChildren = ActivitiesRoute._addFileChildren(
  ActivitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRouteWithChildren,
  BuilderRoute: BuilderRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  FoodRoute: FoodRoute,
  PreviewRoute: PreviewRoute,
  ShoppingListRoute: ShoppingListRoute,
  TodoRoute: TodoRoute,
  TimelineMomentIdRoute: TimelineMomentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
